on: [push, pull_request]

name: Compile

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Archive binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: target/release/
